# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f609a1d1c294d0fc875251e1b1cd0d37ea096d90be31bde19a8a4bb7f7c7e8d8f1a19fa0276285cd463e528fc7acfa7446210d7358c9dba2ed1d963ed5873666

test:
  secret_key_base: 9a32a517765921a237a8344184f253aef2d9256119c382bd4306ea0e6ce32da017ca036d6804f4d647f4ee3811fa30ef9a3ff939967af79ee06b57bf27f55405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
